name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - '.github/workflows/docker.yaml'
      - 'debian/**'
      - 'home/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: finctive/playground:latest